/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ehis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Joe
 */
public class DoctorNursePanel extends javax.swing.JPanel {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    EHIS ehis;

    DoctorNursePanel(String username) {
        initComponents();
        conn = EHIS.getConnection();
        ehis = EHIS.getEhis();
        personalInfoPanel1.setAllFields(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_View_Edit_Calender = new javax.swing.JButton();
        btn_Manage_Patient_Record = new javax.swing.JButton();
        btn_Logout = new ehis.LogoutPanel();
        personalInfoPanel1 = new ehis.PersonalInfoPanel();

        btn_View_Edit_Calender.setText("View/Edit Calendar");
        btn_View_Edit_Calender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_Edit_CalenderActionPerformed(evt);
            }
        });

        btn_Manage_Patient_Record.setText("Manage Patient Record");
        btn_Manage_Patient_Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Manage_Patient_RecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Manage_Patient_Record, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_View_Edit_Calender, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(personalInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(personalInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_View_Edit_Calender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Manage_Patient_Record)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Manage_Patient_RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Manage_Patient_RecordActionPerformed
        PatientRec_NurseDocView panel = new PatientRec_NurseDocView();
        panel.setPanel(this);
        ehis.setContentPane(panel);
        ehis.pack();
        ehis.validate();
        
    }//GEN-LAST:event_btn_Manage_Patient_RecordActionPerformed

    private void btn_View_Edit_CalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_Edit_CalenderActionPerformed
        CalendarDoctor panel = new CalendarDoctor();
        ehis.setContentPane(panel);
        ehis.pack();
        ehis.validate();
    }//GEN-LAST:event_btn_View_Edit_CalenderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ehis.LogoutPanel btn_Logout;
    private javax.swing.JButton btn_Manage_Patient_Record;
    private javax.swing.JButton btn_View_Edit_Calender;
    private ehis.PersonalInfoPanel personalInfoPanel1;
    // End of variables declaration//GEN-END:variables
}
