/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ehis;

import java.sql.ResultSet;

import java.sql.*;
import javax.swing.*;

public class LoginPanel extends javax.swing.JPanel {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    EHIS ehis;
    
    /**
     * Creates new form Login
     */
    public LoginPanel() {
        initComponents();
        conn = Javaconnect.ConnectorDb();
        ehis = EHIS.getEhis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Username = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        btn_New_Account = new javax.swing.JButton();
        btn_Forgot_Username_Password = new javax.swing.JButton();
        EHISLabel = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        btn_New_Account.setText("New Account");
        btn_New_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_New_AccountActionPerformed(evt);
            }
        });

        btn_Forgot_Username_Password.setText("Forgot username/password");

        EHISLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EHISLabel.setText("Electronic Health Information System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txt_Password))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btn_New_Account)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Forgot_Username_Password)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EHISLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EHISLabel)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_New_Account)
                    .addComponent(btn_Forgot_Username_Password))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_New_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_New_AccountActionPerformed
        NewAccountPanel panel = new NewAccountPanel();
        ehis.setContentPane(panel);
        ehis.pack();
        ehis.validate();
    }//GEN-LAST:event_btn_New_AccountActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
       String sql = "Select * from User_Info where Username=? and Password=?";
        try{ 
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_Username.getText());
            pst.setString(2, txt_Password.getText());
            
            rs = pst.executeQuery();
            
            String userType = rs.getString("Usertype");
            //String userType = cmb_Usertype.getSelectedItem().toString();   
            String username = rs.getString("Username");
            String firstname = rs.getString("FirstName");
            String lastname = rs.getString("LastName");
            String address = rs.getString("Address");
            String dob = rs.getString("DOB");
            String phone = rs.getString("Phone");
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Username and Password are correct");
                if(userType.equals("Patient")){
                    PatientPanel panel = new PatientPanel(username,firstname,lastname,address,dob,phone);
                    ehis.setContentPane(panel);
                }
                else if(userType.equals("Receptionist")){
                    ReceptionistPanel panel = new ReceptionistPanel(username,firstname,lastname,address,dob,phone);
                    ehis.setContentPane(panel);
                }
                else if(userType.equals("Nurse")){
                   DoctorNursePanel panel = new DoctorNursePanel(username,firstname,lastname,address,dob,phone);
                   ehis.setContentPane(panel);
                }
                else if(userType.equals("Doctor")){
                   DoctorNursePanel panel= new DoctorNursePanel(username,firstname,lastname,address,dob,phone);
                   ehis.setContentPane(panel);                   
                }
            ehis.pack();
            ehis.validate();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username or Password are invalid");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EHISLabel;
    private javax.swing.JButton btn_Forgot_Username_Password;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_New_Account;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Username;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
