/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ehis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.*;

public class NewAccountPanel extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stat;

    /**
     * Creates new form NewAccountPanel
     */
    public NewAccountPanel() {
        initComponents();

        conn = EHIS.getConnection();

        try {
            stat = conn.createStatement();
            rs = stat.executeQuery("Select * from UserType;");
            while (rs.next()) {
                cmb_usertype.addItem(rs.getString("type"));
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
//        String[] userTypes = {"Patient", "Receptionist", "Nurse","Doctor"};
//        cmb_Usertype.setModel(new DefaultComboBoxModel(userTypes));
    }

    public void clear() {
        txt_FName.setText("");
        txt_LName.setText("");
        txt_username.setText("");
        txt_password.setText("");
        txt_phnum.setText("");
        txt_email.setText("");
        txt_address.setText("");
        txt_dob.setDate(null);
        txt_reenter_password.setText("");
        cmb_usertype.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_create = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmb_usertype = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_FName = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        txt_LName = new javax.swing.JTextField();
        usernameLabel2 = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        txt_reenter_password = new javax.swing.JPasswordField();
        txt_phnum = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dob = new com.toedter.calendar.JDateChooser();

        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        usernameLabel.setText("Username*");

        passwordLabel.setText("Password*");

        passwordLabel1.setText("Re-enter Password*");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Create New Account");

        cmb_usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_usertypeActionPerformed(evt);
            }
        });

        jLabel2.setText("Usertype");

        firstNameLabel.setText("First Name");

        usernameLabel2.setText("Last Name");

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        txt_phnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phnumActionPerformed(evt);
            }
        });

        jLabel3.setText("Date of Birth*");

        jLabel4.setText("Address");

        jLabel5.setText("Email");

        jLabel6.setText("Phone #*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel1)
                            .addComponent(passwordLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(usernameLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_FName)
                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txt_reenter_password)
                            .addComponent(txt_LName))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3)
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_usertype, 0, 132, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txt_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(usernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_address, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txt_email)
                            .addComponent(txt_phnum)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_Back)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel)
                    .addComponent(txt_phnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_reenter_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel1)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel2)
                            .addComponent(cmb_usertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addComponent(btn_create))
                    .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_usertypeActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        EHIS ehis = EHIS.getEhis();
        JPanel loginPanel = EHIS.getLoginPanel();
        ehis.setContentPane(loginPanel);
        ehis.pack();
        ehis.validate();
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed

        String sql;

        String username = txt_username.getText();
        String password = String.valueOf(txt_password.getPassword());
        String passwordRe = String.valueOf(txt_reenter_password.getPassword());
        String firstName = txt_FName.getText();
        String lastName = txt_LName.getText();
        String phoneNum = txt_phnum.getText();
        String email = txt_email.getText();
        String address = txt_address.getText();
        java.util.Date dt_dob = txt_dob.getDate();


        //ENFORCE POLICIES

        //Valid date
        if (dt_dob == null) {
            JOptionPane.showMessageDialog(null, "Invalid DOB");
            return;
        }

        if (!dt_dob.before(new java.util.Date())) {
            JOptionPane.showMessageDialog(null, "Date of Birth needs to be before today!");
            return;
        }
        //String dob = new SimpleDateFormat("MM/dd/yyyy").format(dt_dob);


        //password policies
        boolean hasSpecial, hasUpper, hasDigit, isAtLeastEight;

        isAtLeastEight = password.length() >= 8;
        hasSpecial = Pattern.compile("[!@#$%]").matcher(password).find();
        hasUpper = Pattern.compile("[A-Z]").matcher(password).find();
        hasDigit = Pattern.compile("[0-9]").matcher(password).find();

        if (!hasSpecial || !hasUpper || !hasDigit || !isAtLeastEight) {
            JOptionPane.showMessageDialog(null, "Passwords needs at least eight characters, "
                    + "one upper case letter, one digit, "
                    + "and one of the following characters: ! @ # $ %");
            return;
        }

        //password equal to re-entered password    
        if (!password.equals(passwordRe)) {
            JOptionPane.showMessageDialog(null, "Passwords Not Equal");
            return;
        }

        //phone-number format

        boolean phoneGood = Pattern.compile("^[0-9]{3}-[0-9]{3}-[0-9]{4}$").matcher(phoneNum).find();
        if (!phoneGood) {
            JOptionPane.showMessageDialog(null, "Phone number format must be ###-###-####");
            return;
        }


        try {

            //make sure username isn't already taken
            sql = "SELECT userID FROM Login;";
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                if (username.equals(rs.getString("userID"))) {
                    JOptionPane.showMessageDialog(null, "Username already Taken");
                    return;
                }
            }

            String selecteditem = cmb_usertype.getSelectedItem().toString();
            stat = conn.createStatement();
            sql = "SELECT TypeID FROM UserType WHERE type = '" + selecteditem + "';";
            rs = stat.executeQuery(sql);
            sql = "INSERT INTO Login (userID, Password, FName, LName, PhoneNum, Email, Address, DOB, UserTypeTypeID)"
                    + "VALUES('" + 
                    username  + "','" + 
                    password  + "','" + 
                    firstName + "','" + 
                    lastName  + "','" + 
                    phoneNum  + "','" + 
                    email     + "','" + 
                    address   + "','" + 
                    dt_dob.getTime()+ "','" + 
                    rs.getInt("TypeID") + "');";
            stat.executeUpdate(sql);

            clear();
            JOptionPane.showMessageDialog(null, "New Account Created");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_createActionPerformed

    private void txt_phnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phnumActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_create;
    private javax.swing.JComboBox cmb_usertype;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JTextField txt_FName;
    private javax.swing.JTextField txt_LName;
    private javax.swing.JTextField txt_address;
    private com.toedter.calendar.JDateChooser txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phnum;
    private javax.swing.JPasswordField txt_reenter_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel2;
    // End of variables declaration//GEN-END:variables
}
