/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ehis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class PersonalInfoPanel extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    EHIS ehis = EHIS.getEhis();
    String username;
    /**
     * Creates new form PersonalInfoPanel
     */
    public PersonalInfoPanel() {
        initComponents();
        conn = Javaconnect.ConnectorDb();   
    }
    
    public void setAllFields(String username){
        try{
            this.username = username;
            String sql = "SELECT * from User_Info where Username=?";

            pst = conn.prepareStatement(sql);
            pst.setString(1, username);  
            rs = pst.executeQuery();
            
            //for displaying name on the label
            String firstname = rs.getString("FirstName");
            String lastname = rs.getString("LastName");
            lbl_Name.setText("Name: "+ firstname + " " +lastname);
            
            String address = rs.getString("Address");
            lbl_Address.setText(address);
            
            java.util.Date date = rs.getDate("DOB");           
            java.sql.Date dob = new java.sql.Date(date.getTime());  
            lbl_DOB.setText(dob.toString());
            
            String phone = rs.getString("Phone");
            lbl_Phone.setText(phone);             
            
            JOptionPane.showMessageDialog(null, "Information saved");
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);                    
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Name = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        lbl_DOB = new javax.swing.JLabel();
        lbl_Phone = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JButton();
        lbl_Username = new javax.swing.JLabel();

        lbl_Name.setText("Name: Firstname Lastname");

        lbl_Address.setText("Address: Address");

        lbl_DOB.setText("DOB: 11/14/11");

        lbl_Phone.setText("Phone: 222-1212");

        btn_Edit.setText("Edit");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        lbl_Username.setText("Username: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Edit))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name)
                    .addComponent(lbl_Username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_DOB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Edit)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        JDialog dialog = new JDialog(ehis, "Personal Info Edit", true);
        PersonalInfoEditPanel panel = new PersonalInfoEditPanel(username, dialog);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setVisible(true);
        
    }//GEN-LAST:event_btn_EditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Edit;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_DOB;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_Username;
    // End of variables declaration//GEN-END:variables
}
