/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ehis;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


    /**
 *
 * @author Joe
 */
public class ReceptionistPanel extends javax.swing.JPanel {

    Vector<String> patientIDs = new Vector<>();
    Vector<String> patientNames = new Vector<>();

    /**
     * Creates new form ReceptionistPanel
     */
    public ReceptionistPanel() {
        initComponents();
        fillPatientList();
    }

    ReceptionistPanel(String username) {
        this();
    }

    public void fillPatientList() {
        try {
            Statement stat = EHIS.getConnection().createStatement();
            String sql = "SELECT userID, FName, LName FROM Login JOIN UserType on UserType.TypeID = Login.UserTypeTypeID WHERE userType.type = 'Patient';";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                patientIDs.add(rs.getString("userID"));
                patientNames.add(rs.getString("FName") + " " + rs.getString("LName"));
            }
            listPatient.setListData(patientNames);

        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        listPatient.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index = listPatient.getSelectedIndex();
                patientRec_PatRecepView1.getPersonalInfoPanel().setAllFields(patientIDs.get(index));
                patientRec_PatRecepView1.setPatientID(patientIDs.get(index));
                
                try {
            Statement stat = EHIS.getConnection().createStatement();
            String sql = "SELECT * FROM apppointment WHERE LoginPatientID = '" + patientIDs.get(index) + "';";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                
            }
            listPatient.setListData(patientNames);

        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                validate();
            }
        }

    
);
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientRec_PatRecepView1 = new ehis.PatientRec_PatRecepView();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPatient = new javax.swing.JList();
        logoutPanel1 = new ehis.LogoutPanel();

        jLabel1.setText("Choose Patient:");

        listPatient.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPatientValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPatient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(logoutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(patientRec_PatRecepView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientRec_PatRecepView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listPatientValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPatientValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listPatientValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listPatient;
    private ehis.LogoutPanel logoutPanel1;
    private ehis.PatientRec_PatRecepView patientRec_PatRecepView1;
    // End of variables declaration//GEN-END:variables
}
